language: python

services:
  - docker

before_install:
- sudo apt-get -y install expect
- ./script_generate_certs.sh fake_key
- find oidc/data -type d -exec chmod 777 {} \;
- ls -ld oidc/data/*
- docker-compose up -d
- ./script_wait_keycloak.sh
- pip install -r tests/requirements.txt

script:
- pytest tests