language: python

services:
  - docker

before_install:
- sudo apt-get -y install expect
- pip install -r tests/requirements.txt
- find oidc/data -type d -exec chmod 777 {} \;
- ./script_generate_certs.sh fake_key
- docker-compose up -d
- ./script_wait_keycloak.sh

script:
- pytest tests
- docker-compose logs