language: python

env:
  - OIDC1="http://localhost:8080/auth/realms/mockrealm/protocol/openid-connect"
  - OIDC2="http://localhost:8081/auth/realms/mockrealm/protocol/openid-connect"
  - OIDC1_OPENCONNECT="http://localhost:8080/auth/realms/mockrealm/protocol/openid-connect"
  - OIDC2_OPENCONNECT="http://localhost:8081/auth/realms/mockrealm/protocol/openid-connect"
services:
  - docker

cache:
  directories:
  - docker_images
git:
  submodules: false

before_install:
- docker load -i docker_images/images.tar || true
- pip install -r tests/requirements.txt
- git submodule update --init --recursive

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

install:
- touch permissions_engine/data.json
- sudo apt-get -y install expect
- ./script_generate_certs.sh fake_key
- docker-compose up -d
- ./script_wait_keycloak.sh
- ./oidc/config-oidc-service
- ./script_wait_keycloak.sh
- python3 permissions_engine/fetch_keys.py
- python3 tests/create_katsu_test_datasets.py
- docker-compose restart opa

script:
- pytest tests/katsu_tests
- docker-compose logs
