language: python

services:
  - docker

before_install:
- sudo apt-get -y install expect
- pip install -r tests/requirements.txt
- ./script_generate_certs.sh fake_key
- docker-compose up -d
- ./script_wait_keycloak.sh
- ./oidc/config-oidc-service
- ./script_wait_keycloak.sh

script:
- pytest tests
- docker-compose logs