version: '3'
services:
  fake_beacon:
    build: fake_beacon
    ports:
      - "8000:80"
    volumes:
      - ./rootCA.crt:/rootCA.crt
    environment:
      ROOT_CA: /rootCA.crt
      IDP: https://oidc:8443/auth/realms/mockrealm/protocol/openid-connect
      IDP_CLIENT_ID: mock_login_client
      IDP_CLIENT_SECRET: mock_login_secret
      PERMISSIONS_SERVER: https://opa:8181/v1/data/permissions/datasets
      PERMISSIONS_SECRET: my-secret-beacon-token

  oidc:
    container_name: oidc
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./oidc/tls.crt:/etc/x509/https/tls.crt
      - ./oidc/tls.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./permissions_engine/permissions.rego:/policy.rego
      - ./permissions_engine/idp.rego:/idp.rego
      - ./permissions_engine/authz.rego:/authz.rego
      - ./permissions_engine/tls.crt:/public.crt
      - ./permissions_engine/tls.key:/private.key
      - ./rootCA.crt:/rootCA.crt
    environment:
      IDP: https://oidc:8443/auth/realms/mockrealm/
      ROOT_CA: /rootCA.crt
      IDP_CLIENT_ID: mock_permissions_client
      IDP_CLIENT_SECRET: mockpermissions_secret
      CLIENT_SECRET_ROOT: my-secret-root-token
      CLIENT_SECRET_BEACON: my-secret-beacon-token
    command:
      - "run"
      - "--server"
      - "--addr"
      - "https://0.0.0.0:8181"
      - "--log-level=info"
      - "--tls-cert-file=/public.crt"
      - "--tls-private-key-file=/private.key"
      - "--authentication=token"
      - "--authorization=basic"
      - "/authz.rego"
      - "/policy.rego"
      - "/idp.rego"