version: '3'
services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./permissions_engine/permissions.rego:/policy.rego
      - ./permissions_engine/idp.rego:/idp.rego
      - ./permissions_engine/authz.rego:/authz.rego
      - ./permissions_engine/tls.crt:/public.crt
      - ./permissions_engine/tls.key:/private.key
      - ./permissions_engine/data.json:/data.json
      - ./rootCA.crt:/rootCA.crt
    environment:
      IDP: https://auth.docker.localhost:8443/auth/realms/candig/
      ROOT_CA: /rootCA.crt
      IDP_CLIENT_ID: mock_permissions_client
      IDP_CLIENT_SECRET: mockpermissions_secret
      CLIENT_SECRET_ROOT: my-secret-root-token
      CLIENT_SECRET_SERVICE: my-secret-service-token
    command:
      - "run"
      - "--server"
      - "--addr"
      - "https://0.0.0.0:8181"
      - "--log-level=debug"
      - "--tls-cert-file=/public.crt"
      - "--tls-private-key-file=/private.key"
      - "--authentication=token"
      - "--authorization=basic"
      - "/authz.rego"
      - "/policy.rego"
      - "/idp.rego"
      - "/data.json"
    networks:
      - bridge-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8181" ]
      interval: 30s
      timeout: 20s
      retries: 3
