version: '3'
services:
  fake_beacon:
    build: fake_beacon
    ports:
      - "8000:80"
    volumes:
      - ./rootCA.crt:/rootCA.crt
    environment:
      ROOT_CA: /rootCA.crt
      IDP: https://oidc1:8443/auth/realms/mockrealm/protocol/openid-connect https://oidc2:8443/auth/realms/mockrealm/protocol/openid-connect
      IDP_CLIENT_ID: mock_login_client
      IDP_CLIENT_SECRET: mock_login_secret
      PERMISSIONS_SHIM: https://shim:8180/permissions
      PERMISSIONS_SECRET: my-secret-beacon-token

  oidc1:
    container_name: oidc1
    image: jboss/keycloak
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./oidc/tls_oidc1.crt:/etc/x509/https/tls.crt
      - ./oidc/tls_oidc1.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin
      USER1: user1
      USER1PWD: pass1
      USER2: user2
      USER2PWD: pass2
  oidc2:
    container_name: oidc2
    image: jboss/keycloak
    ports:
      - "8081:8080"
      - "8444:8443"
    volumes:
      - ./oidc/tls_oidc2.crt:/etc/x509/https/tls.crt
      - ./oidc/tls_oidc2.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_USER: kcadmin
      KEYCLOAK_PASSWORD: admin
      USER1: user3
      USER1PWD: pass3
      USER2: user4
      USER2PWD: pass4
  shim:
    build: permissions_shim
    ports:
      - "8180:8180"
    volumes:
      - ./rootCA.crt:/rootCA.crt
      - ./permissions_shim/tls.crt:/tls.crt
      - ./permissions_shim/tls.key:/tls.key
    command:
      - "--host=0.0.0.0"
      - "--port=8180"
      - "--tls_key=/tls.key"
      - "--tls_cert=/tls.crt"
    environment:
      PERMISSIONS_ENGINE: https://opa:8181/v1/data/permissions/datasets
      ROOT_CA: /rootCA.crt

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    volumes:
      - ./permissions_engine/permissions.rego:/policy.rego
      - ./permissions_engine/idp.rego:/idp.rego
      - ./permissions_engine/authz.rego:/authz.rego
      - ./permissions_engine/tls.crt:/public.crt
      - ./permissions_engine/tls.key:/private.key
      - ./permissions_engine/data.json:/data.json
      - ./rootCA.crt:/rootCA.crt
    environment:
      IDP: https://oidc1:8443/auth/realms/mockrealm/ https://oidc2:8443/auth/realms/mockrealm/
      ROOT_CA: /rootCA.crt
      IDP_CLIENT_ID: mock_permissions_client
      IDP_CLIENT_SECRET: mockpermissions_secret
      CLIENT_SECRET_ROOT: my-secret-root-token
      CLIENT_SECRET_BEACON: my-secret-beacon-token
    command:
      - "run"
      - "--server"
      - "--addr"
      - "https://0.0.0.0:8181"
      - "--log-level=info"
      - "--tls-cert-file=/public.crt"
      - "--tls-private-key-file=/private.key"
      - "--authentication=token"
      - "--authorization=basic"
      - "/authz.rego"
      - "/policy.rego"
      - "/idp.rego"
      - "/data.json"
