version: '3'
services:
    oidc-server-mock:
      container_name: oidc
      image: jboss/keycloak
      ports:
        - "8080:8080"
      environment:
        KEYCLOAK_USER: kcadmin
        KEYCLOAK_PASSWORD: admin
